/* Hildana. M
 * CalculatorGadget_Culminating.java
 * This program is called the Calculator Gadget. It allows the user 
 * to use a simple calculator, a temperature converter, a unit converter
 * and a currency converter 
 * June/19/2018
 */

/**
 *
 * @author Hildana
 */
public class FrameCalculatorGadget_Culminating extends javax.swing.JFrame {

    /**
     * Creates new form FrameCalculatorGadget_Culminating
     */
    public FrameCalculatorGadget_Culminating() {
        initComponents();
        //sets the program in the middle of the screen 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCalculatorGadget = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInstruction = new javax.swing.JTextArea();
        buttonCalculator = new javax.swing.JButton();
        buttonTemperature = new javax.swing.JButton();
        buttonUnit = new javax.swing.JButton();
        buttonCurrency = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        labelCalculatorGadget.setFont(new java.awt.Font("Stencil", 0, 55)); // NOI18N
        labelCalculatorGadget.setText("The Calculator Gadget ");

        jScrollPane1.setHorizontalScrollBar(null);

        textAreaInstruction.setEditable(false);
        textAreaInstruction.setColumns(20);
        textAreaInstruction.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textAreaInstruction.setLineWrap(true);
        textAreaInstruction.setRows(5);
        textAreaInstruction.setText("Welcome to The Calculator Gadget!\n\nThis software will allow you to use a calculator, a temperature converter, a unit converter and a currency converter.\n\nJust press on of those buttons to go to the desired page.\n  \n\n");
        textAreaInstruction.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaInstruction);

        buttonCalculator.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonCalculator.setText("Calculator");
        buttonCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculatorActionPerformed(evt);
            }
        });

        buttonTemperature.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTemperature.setText("Temperature Converter");
        buttonTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTemperatureActionPerformed(evt);
            }
        });

        buttonUnit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonUnit.setText("Unit Converter");
        buttonUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUnitActionPerformed(evt);
            }
        });

        buttonCurrency.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonCurrency.setText("Currency Converter");
        buttonCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCurrencyActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCalculatorGadget)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonUnit)
                            .addComponent(buttonTemperature)
                            .addComponent(buttonCalculator)
                            .addComponent(buttonCurrency))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelCalculatorGadget)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(buttonCalculator)
                        .addGap(31, 31, 31)
                        .addComponent(buttonTemperature)
                        .addGap(38, 38, 38)
                        .addComponent(buttonUnit)
                        .addGap(42, 42, 42)
                        .addComponent(buttonCurrency))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculatorActionPerformed
    
        //open new frame when user presses the button 
        this.setVisible(false);
        new  NewJFrame1().setVisible(true);
        
    }//GEN-LAST:event_buttonCalculatorActionPerformed

    private void buttonTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTemperatureActionPerformed
        
        //open new frame when user presses the button 
        this.setVisible(false);
        new  NewJFrame2().setVisible(true);
        
    }//GEN-LAST:event_buttonTemperatureActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void buttonUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUnitActionPerformed
       
        //open new frame when user presses the button 
        this.setVisible(false);
        new  NewJFrame3().setVisible(true);
        
    }//GEN-LAST:event_buttonUnitActionPerformed

    private void buttonCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCurrencyActionPerformed
       
        //open new frame when user presses the button 
        this.setVisible(false);
        new  NewJFrame4().setVisible(true);
        
    }//GEN-LAST:event_buttonCurrencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCalculatorGadget_Culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCalculatorGadget_Culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCalculatorGadget_Culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCalculatorGadget_Culminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCalculatorGadget_Culminating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculator;
    private javax.swing.JButton buttonCurrency;
    private javax.swing.JButton buttonTemperature;
    private javax.swing.JButton buttonUnit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCalculatorGadget;
    private javax.swing.JTextArea textAreaInstruction;
    // End of variables declaration//GEN-END:variables
}
