
import java.text.DecimalFormat;

/*
 * This is the units converter. The user will be able to convert from imperial
 * to metric and vice verca 
 */

/**
 *
 * @author Hildana
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
        //sets the program in the middle of the screen 
        this.setLocationRelativeTo(null);
    }
    
     /**
     * Converts metric units to imperial 
     * return the imperial result
     */  
    public double metricToImperial(double unit)
    {
        double result = 0;
        
        //round the output to two decimal places
        DecimalFormat round = new DecimalFormat ("###.##");
        
        
        /**
         * The code bellow is for the 
         * length measurement conversions 
         */
        
        //Centimeter to Inches 
        if (buttonMetToImp.isSelected() && buttonCI.isSelected())
        {
           result = unit * 0.393701;
           lableResult.setText(unit + " centimeters = " + round.format(result) + " inches");
        } 
        
        //Meter to Yards
        if (buttonMetToImp.isSelected() && buttonMY.isSelected())
        {
           result = unit * 1.09361;
           lableResult.setText(unit + " meters = " + round.format(result) + " yards");
        }
        
        //Kilometer to miles 
        if (buttonMetToImp.isSelected() && buttonKM.isSelected())
        {
           result = unit * 0.62136931818182;
           lableResult.setText(unit + " kilometers = " + round.format(result) + " miles");
        }
        
        
        /**
         * The code bellow is for the 
         * mass measurement conversions 
         */
        
        //Gram to Ounce
        if (buttonMetToImp.isSelected() && buttonGO.isSelected())
        {
           result = unit * 0.035274;
           lableResult.setText(unit + " grams = " + round.format(result) + " ounce");
        }
        
        //Milligram to grain 
        if (buttonMetToImp.isSelected() && buttonMG.isSelected())
        {
           result = unit * 0.0154324;
           lableResult.setText(unit + " milligrams = " + round.format(result) + " grains");
        }
        
        //Kilogram to pounds
        if (buttonMetToImp.isSelected() && buttonKP.isSelected())
        {
           result = unit * 2.20462;
           lableResult.setText(unit + " kilograms = " + round.format(result) + " pounds");
        }
        
        return result;
    }
    
    /**
     * Converts imperial units to metric
     * return the metric results
     */ 
    public double imperialToMetric(double unit)
    {
       double result = 0;
       
       //round the output to two decimal places
        DecimalFormat round = new DecimalFormat ("###.##");
       
       /**
        * The code bellow is for the 
        * length measurement conversions 
        */
        
       //Inches to centimeter
       if (buttonImpToMet.isSelected() && buttonCI.isSelected())
       {
           result = unit * 2.4;
           lableResult.setText(unit + " inches = " + round.format(result) + " centimeters");
       }
       
       //Yards to meters 
       if (buttonImpToMet.isSelected() && buttonMY.isSelected())
       {
           result = unit * 0.9144;
           lableResult.setText(unit + " yards = " + round.format(result) + " meters");
       }
       
       //Mile to kilometers
       if (buttonImpToMet.isSelected() && buttonKM.isSelected())
       {
           result = unit * 1.60934;
           lableResult.setText(unit + " miles = " + round.format(result) + " kilometers");
       }
       
       /**
         * The code bellow is for the 
         * mass measurement conversions 
         */
       
       //Ounce to grams
       if (buttonImpToMet.isSelected() && buttonGO.isSelected())
       {
           result = unit * 28.3495;
           lableResult.setText(unit + " ounce = " + round.format(result) + " grams");
       }
       
       //Grain to milligram
       if (buttonImpToMet.isSelected() && buttonMG.isSelected())
       {
           result = unit * 64.7989;
           lableResult.setText(unit + " grains = " + round.format(result) + " milligrams");
       }
       
       //Pounds to kilogram
       if (buttonImpToMet.isSelected() && buttonKP.isSelected())
       {
           result = unit * 0.453592;
           lableResult.setText(unit + " pounds = " + round.format(result) + " kilograms");
       }
       
       return result;
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lableCent = new javax.swing.JLabel();
        lableInc = new javax.swing.JLabel();
        labelMet = new javax.swing.JLabel();
        lableYar = new javax.swing.JLabel();
        lableKilom = new javax.swing.JLabel();
        lableMil = new javax.swing.JLabel();
        buttonCI = new javax.swing.JRadioButton();
        buttonMY = new javax.swing.JRadioButton();
        buttonKM = new javax.swing.JRadioButton();
        lableLength = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lableMilli = new javax.swing.JLabel();
        lableGra = new javax.swing.JLabel();
        lableKilog = new javax.swing.JLabel();
        lablePou = new javax.swing.JLabel();
        lableOun = new javax.swing.JLabel();
        buttonMG = new javax.swing.JRadioButton();
        buttonGO = new javax.swing.JRadioButton();
        buttonKP = new javax.swing.JRadioButton();
        lableGrain = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        buttonImpToMet = new javax.swing.JRadioButton();
        buttonMetToImp = new javax.swing.JRadioButton();
        textInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lableResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 0, 48)); // NOI18N
        jLabel1.setText("Unit Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lableCent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableCent.setText("Centimeter");

        lableInc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableInc.setText("Inches");

        labelMet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMet.setText("Meter");

        lableYar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableYar.setText("Yards");

        lableKilom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableKilom.setText("Kilometer");

        lableMil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableMil.setText("Miles");

        buttonGroup1.add(buttonCI);
        buttonCI.setToolTipText("");
        buttonCI.setActionCommand("");

        buttonGroup1.add(buttonMY);
        buttonMY.setToolTipText("");

        buttonGroup1.add(buttonKM);
        buttonKM.setToolTipText("");

        lableLength.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lableLength.setText("Length Measurment ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Mass Measurements");

        lableMilli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableMilli.setText("Milligram");

        lableGra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableGra.setText("Gram");

        lableKilog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableKilog.setText("Kilogram");

        lablePou.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lablePou.setText("Pounds");

        lableOun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableOun.setText("Ounce");

        buttonGroup1.add(buttonMG);
        buttonMG.setToolTipText("");

        buttonGroup1.add(buttonGO);
        buttonGO.setToolTipText("");

        buttonGroup1.add(buttonKP);
        buttonKP.setToolTipText("");

        lableGrain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableGrain.setText("Grain");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lableCent)
                        .addGap(27, 27, 27)
                        .addComponent(buttonCI))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelMet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMY))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lableKilom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKM)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableInc)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lableMil)
                        .addComponent(lableYar)))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lableLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableMilli)
                            .addComponent(lableGra)
                            .addComponent(lableKilog))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonKP)
                            .addComponent(buttonGO)
                            .addComponent(buttonMG))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lablePou)
                            .addComponent(lableOun)
                            .addComponent(lableGrain))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lableLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableCent)
                            .addComponent(buttonCI))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMet)
                                .addComponent(lableYar))
                            .addComponent(buttonMY))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonKM)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lableKilom)
                                .addComponent(lableMil))))
                    .addComponent(lableInc, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableMilli)
                            .addComponent(buttonMG))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableGra)
                                    .addComponent(buttonGO))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableKilog)
                                    .addComponent(buttonKP)
                                    .addComponent(lablePou)))
                            .addComponent(lableOun)))
                    .addComponent(lableGrain))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Metric (SI)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Imperial");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("INSTRUCTIONS\n\n1. Choose the type of conversion by selecting one of the two radio button in the middle of the screen.\n\n2. Choose the  measurment conversion by selecting one of the radio buttons to the left of the screen  \n\n3. Input the measurment in the box\n\n4. Press the convert button ");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup2.add(buttonImpToMet);
        buttonImpToMet.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        buttonImpToMet.setText("Imperial to Metric");

        buttonGroup2.add(buttonMetToImp);
        buttonMetToImp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        buttonMetToImp.setText("Metric to Imperial ");

        textInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMetToImp)
                    .addComponent(buttonImpToMet))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMetToImp)
                .addGap(30, 30, 30)
                .addComponent(buttonImpToMet)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lableResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lableResult, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(396, 396, 396))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(buttonBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(buttonBack)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        
        //When user presses this button, it should go back to the homepage 
        this.setVisible(false);
        new  FrameCalculatorGadget_Culminating().setVisible(true);
        
        
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double value;
        
        //What the user typed in 
        value = Double.parseDouble(textInput.getText());
        
        //executes the conversions from metric to imperial
        metricToImperial(value);
        
        //executes the conversions from imperial to metris
        imperialToMetric(value);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JRadioButton buttonCI;
    private javax.swing.JRadioButton buttonGO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton buttonImpToMet;
    private javax.swing.JRadioButton buttonKM;
    private javax.swing.JRadioButton buttonKP;
    private javax.swing.JRadioButton buttonMG;
    private javax.swing.JRadioButton buttonMY;
    private javax.swing.JRadioButton buttonMetToImp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelMet;
    private javax.swing.JLabel lableCent;
    private javax.swing.JLabel lableGra;
    private javax.swing.JLabel lableGrain;
    private javax.swing.JLabel lableInc;
    private javax.swing.JLabel lableKilog;
    private javax.swing.JLabel lableKilom;
    private javax.swing.JLabel lableLength;
    private javax.swing.JLabel lableMil;
    private javax.swing.JLabel lableMilli;
    private javax.swing.JLabel lableOun;
    private javax.swing.JLabel lablePou;
    private javax.swing.JLabel lableResult;
    private javax.swing.JLabel lableYar;
    private javax.swing.JTextField textInput;
    // End of variables declaration//GEN-END:variables
}
