
import java.text.DecimalFormat;

/*
 * This is the temperature converter. The user will be able to convert temperature 
 * such as Celcius, fahrenheit, and kelvin.
 */

/**
 *
 * @author Hildana
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
        //sets the program in the middle of the screen 
        this.setLocationRelativeTo(null);
    }
    
     /**
     * Converts different different temperatures
     * returns the results of those conversions
     */
    public double tempConv(double temp)
    {
       double result = 0;
       
        //round the output to two decimal places
        DecimalFormat round = new DecimalFormat ("###.##");
       
       //Fahrenheit to Celcius 
       if (buttonFF.isSelected() && buttonTC.isSelected())
       {
          result = (temp - 32) / 1.8;  
          labelResult.setText("The temperature is: " + round.format(result) + " celcius");
       
       }
      
       //Fahrenheit to kelvin 
       if (buttonFF.isSelected() && buttonTK.isSelected())
       {
          result = (temp + 459.67) * (0.55555);  
          labelResult.setText("The temperature is: " + round.format(result) + " Kelvin");
     
       }
       
       //Fahrenheit to fahrenheit
       if (buttonFF.isSelected() && buttonTF.isSelected())
       {
          result = temp;
          labelResult.setText("The temperature is: " + temp + " fahrenheit" );
       }
       
       //Celcius to fahrenheit
       if (buttonFC.isSelected() && buttonTF.isSelected())
       {
          result = (temp * 1.8) + 32;
          labelResult.setText("The temperature is: " + round.format(result) + " Fahrenheit");
       }
       
       //Celcius to kelvin 
       if (buttonFC.isSelected() && buttonTK.isSelected())
       {
          result =  temp + 273.15;
          labelResult.setText("The temperature is: " + round.format(result) + " Kelvin");
       }
       
       //Celcius to Celcius 
       if (buttonFC.isSelected() && buttonTC.isSelected())
       {
          result = temp;
          labelResult.setText("The temperature is: " + temp + " celcius");
       }
       
       //Kelvin to Fahrenheit  
       if (buttonFK.isSelected() && buttonTF.isSelected())
       {
          result = (temp * 1.8) - 459.67;
          labelResult.setText("The temperature is: " + round.format(result) + " Fahrenheit");
       }  
       
       //Kelvin to Celcius  
       if (buttonFK.isSelected() && buttonTC.isSelected())
       {
          result = temp - 273.15;
          labelResult.setText("The temperature is: " + round.format(result) + " Celcius");
       } 
       
       //Kelvin to Kelvin
       if (buttonFK.isSelected() && buttonTK.isSelected())
       {
          result = temp;
          labelResult.setText("The temperature is: " + temp + " kelvin");
       }
       
       
       return result; 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelTemperature = new javax.swing.JLabel();
        textEnterTemp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonFF = new javax.swing.JRadioButton();
        buttonFC = new javax.swing.JRadioButton();
        buttonFK = new javax.swing.JRadioButton();
        labelFrom = new javax.swing.JLabel();
        labelEnter = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonTF = new javax.swing.JRadioButton();
        buttonTC = new javax.swing.JRadioButton();
        buttonTK = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        labelResult = new javax.swing.JLabel();
        labelR = new javax.swing.JLabel();
        buttonConverter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        labelTemperature.setFont(new java.awt.Font("Sitka Subheading", 0, 48)); // NOI18N
        labelTemperature.setText("Temperature Converter ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(labelTemperature)
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(labelTemperature))
        );

        textEnterTemp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textEnterTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterTempActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 153, 204))); // NOI18N

        buttonGroup1.add(buttonFF);
        buttonFF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonFF.setText("Fahrenheit");
        buttonFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFFActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonFC);
        buttonFC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonFC.setText("Celcius ");
        buttonFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFCActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonFK);
        buttonFK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonFK.setText("Kelvin ");
        buttonFK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFK)
                    .addComponent(buttonFC)
                    .addComponent(buttonFF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFF)
                .addGap(8, 8, 8)
                .addComponent(buttonFC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFK)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        labelFrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelFrom.setText("From: ");

        labelEnter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEnter.setText("Enter:");

        labelTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTo.setText("To:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 153, 204))); // NOI18N

        buttonGroup2.add(buttonTF);
        buttonTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTF.setText("Fahrenheit");

        buttonGroup2.add(buttonTC);
        buttonTC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTC.setText("Celcius ");

        buttonGroup2.add(buttonTK);
        buttonTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTK.setText("Kelvin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTK)
                    .addComponent(buttonTC)
                    .addComponent(buttonTF))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonTF)
                .addGap(18, 18, 18)
                .addComponent(buttonTC)
                .addGap(18, 18, 18)
                .addComponent(buttonTK)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelResult.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonConverter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonConverter.setText("Convert");
        buttonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverterActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("INSTRUCTIONS\n\n1. Choose the temperature you want to convert from\nby selecting one one the radio buttons\n\n2. Choose the temperature you want to convert to\nby selecting one the radio buttons \n\n3. Enter your temperature\n\n4. Press the convert button.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTo)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(labelFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonConverter)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEnterTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonBack)
                .addContainerGap(1058, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(268, 268, 268))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonConverter)
                                        .addGap(30, 30, 30)))
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelFrom)
                                            .addComponent(labelEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textEnterTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTo))))
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(buttonBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        
        //When the user presses this button, it should go back to the homepage 
        this.setVisible(false);
        new  FrameCalculatorGadget_Culminating().setVisible(true);
        
    }//GEN-LAST:event_buttonBackActionPerformed

    private void textEnterTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterTempActionPerformed
       
    }//GEN-LAST:event_textEnterTempActionPerformed

    private void buttonFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFFActionPerformed
    
       
    }//GEN-LAST:event_buttonFFActionPerformed

    private void buttonFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFCActionPerformed
        
    }//GEN-LAST:event_buttonFCActionPerformed

    private void buttonFKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFKActionPerformed
        
    }//GEN-LAST:event_buttonFKActionPerformed

    private void buttonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverterActionPerformed
        double value;
        
        value = Double.parseDouble(textEnterTemp.getText());
      
        //executes the conversions when the button is pressed 
        tempConv(value);
    }//GEN-LAST:event_buttonConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonConverter;
    private javax.swing.JRadioButton buttonFC;
    private javax.swing.JRadioButton buttonFF;
    private javax.swing.JRadioButton buttonFK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton buttonTC;
    private javax.swing.JRadioButton buttonTF;
    private javax.swing.JRadioButton buttonTK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelEnter;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelR;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelTemperature;
    private javax.swing.JLabel labelTo;
    private javax.swing.JTextField textEnterTemp;
    // End of variables declaration//GEN-END:variables
}
